services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
