services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
      - "9222:9222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
    command: ["-c", "/etc/nats/nats.conf"]

  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: ["-varz", "-jsz", "all", "-DV", "http://nats:8222"]
    depends_on:
      - nats

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver

  tempo:
    image: grafana/tempo:2.2.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # Tempo
    expose:
      - "4317"
      - "4318"

  # Prometheus (Metrics)
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana (Visualization)
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-dashboards-config.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards/json

  rpc-server:
    build:
      context: ..
      target: rpc-server
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - nats
      - otel-collector

  order-service:
    build:
      context: ..
      target: order-service
    environment:
      - NATS_URL=nats://nats:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - nats
      - otel-collector

  payment-service:
    build:
      context: ..
      target: payment-service
    environment:
      - NATS_URL=nats://nats:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - nats
      - otel-collector

  shipping-service:
    build:
      context: ..
      target: shipping-service
    environment:
      - NATS_URL=nats://nats:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - nats
      - otel-collector

  analytics-service:
    build:
      context: ..
      target: analytics-service
    environment:
      - NATS_URL=nats://nats:4222
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - nats
      - otel-collector

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"
    depends_on:
      - nats
      - rpc-server
