name: "My JavaScript Action"
description: "An action that outputs a greeting time"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "index.js"
