services:
  - name: auth
    port: 3000
    dbName: auth_db
    image:
      repository: event-platform/auth
      tag: latest
  - name: org
    port: 3001
    dbName: org_db
    image:
      repository: event-platform/org
      tag: latest
  - name: scheduler
    port: 3002
    dbName: scheduler_db
    image:
      repository: event-platform/scheduler
      tag: latest
  - name: mock-executor
    port: 3003
    dbName: none
    image:
      repository: event-platform/mock-executor
      tag: latest
  - name: gateway
    port: 8080
    dbName: none
    image:
      repository: event-platform/gateway
      tag: latest

services_base_repo: event-platform
image_tag: latest

frontend:
  image:
    repository: event-platform/frontend
    tag: latest

nats:
  enabled: true
mongodb:
  enabled: true
