services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  cache:
    image: valkey/valkey:latest
    ports:
      - "6379:6379" # Redis default port
    volumes:
      - ./valkey.conf:/etc/valkey/valkey.conf # Mount your custom config
      - valkey_data:/data # Persist Redis data
    command: ["valkey-server", "/etc/valkey/valkey.conf"]
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "valkey-cli", "-u", "redis://user:password@localhost:6379", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432" # PostgreSQL default port
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure # Ensure postgres restarts if it fails

  go_backend:
    build:
      context: ./app # Path to your Go application directory
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080" # Port for the Go application
    environment:
      # Connection string for PostgreSQL from the perspective of the Go container.
      # 'host' is 'postgres' because that's the service name in docker-compose.
      DATABASE_URL: "host=postgres user=user password=password dbname=mydatabase port=5432 sslmode=disable"
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy # Ensure postgres is healthy before starting go_backend
      cache:
        condition: service_healthy # Ensure postgres is healthy before starting go_backend
    restart: on-failure # Ensure the backend restarts if it fails

  go_worker:
    build:
      context: ./app # Path to your Go application directory
      dockerfile: worker.Dockerfile
    environment:
      CACHE_ADDRESS: redis://user:password@cache:6379/0?protocol=3
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy # Ensure postgres is healthy before starting go_backend
      cache:
        condition: service_healthy # Ensure postgres is healthy before starting go_backend
    restart: on-failure # Ensure the backend restarts if it fails
networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
  valkey_data:
  postgres_data:

