services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # HTTP management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-net

  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  rabbitmq_data:
  valkey_data:
