apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: health-check
  annotations:
    version: v0.1.0
    description: "Health check probe registry component"
spec:
  components:
    - name: health-check-component
      type: component
      properties:
        image: file://../target/wasm32-wasip2/release/health_check_component.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
