apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: tracing
  annotations:
    version: v0.1.0
    description: "Correlation ID and request tracing component"
spec:
  components:
    - name: tracing-component
      type: component
      properties:
        image: file://../target/wasm32-wasip2/release/tracing_component.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
