apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-external
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.services_base_repo }}/gateway:{{ .Values.image_tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth:3000"
            - name: ORG_SERVICE_URL
              value: "http://org:3001"
            - name: SCHEDULER_SERVICE_URL
              value: "http://scheduler:3002"
            - name: APP_NATS__URL
              value: "nats://nats:4222"
            - name: APP_MONGODB__URL
              value: "mongodb://admin:password@mongodb:27017"
            - name: APP_AUTH__JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: jwt-secret
