apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: sliding-window-ratelimiter
  annotations:
    version: v0.1.0
    description: "Sliding Window Rate Limiter Component"
spec:
  components:
    - name: sliding-window
      type: component
      properties:
        image: file://../target/wasm32-wasip1/release/sliding_window.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats-kv
            namespace: wasi
            package: keyvalue
            interfaces:
              - store
              - atomics
            target_config:
              - name: default-bucket
                properties:
                  bucket: ratelimit-sliding-window

    - name: nats-kv
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-nats:0.3.1
