apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: token-bucket-ratelimiter
  annotations:
    version: v0.1.0
    description: "Token Bucket Rate Limiter Component"
spec:
  components:
    - name: token-bucket
      type: component
      properties:
        image: file://../target/wasm32-wasip1/release/token_bucket.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats-kv
            namespace: wasi
            package: keyvalue
            interfaces:
              - store
              - atomics
            target_config:
              - name: default-bucket
                properties:
                  bucket: ratelimit-token-bucket

    - name: nats-kv
      type: capability
      properties:
        image: ghcr.io/wasmcloud/keyvalue-nats:0.3.1
