name: "petclinic-django"

on:
  pull_request:
    paths:
      - "petClinic-django/**"

jobs:
  runCI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fastapi-pg
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: steup uv
        uses: astral-sh/setup-uv@v5
      - name: install packages
        run: uv sync --frozen
      - name: build app
        run: uv build
      - name: run linter
        run: uv run ruff check
      # - name: run tests
      #   run: uv run pytest
      # - name: run bdd tests
      #   run: uv run behave

