name: "sequelize-testcontainer-migrations-ci"

on:
  pull_request:
    paths:
      - "sequelize-testcontainer-migrations/**"

jobs:
  runCI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sequelize-testcontainer-migrations
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - name: install packages
        run: npm install
      - name: run npm build
        run: npm run check
      - name: run checks
        run: npm run check
      - name: run tests
        run: npm run test
