name: "tc-python-demo-ci"

on:
  pull_request:
    paths:
      - "tc-python-demo/**"

jobs:
  runCI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tc-python-demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest
      - name: install packages
        run: poetry sync --no-root
      - name: run linter
        run: poetry run ruff check
      - name: run tests
        run: poetry run pytest
      - name: run bdd tests
        run: poetry run behave